---
- include: linux/install-dependencies-apt.yml
  when: ansible_pkg_mgr == "apt"
- include: linux/install-dependencies-yum.yml
  when: ansible_pkg_mgr == "yum"

- include: linux/install-dynatrace-glassfish-agent.yml

- include: linux/remove-dependencies-apt.yml
  when: ansible_pkg_mgr == "apt"
- include: linux/remove-dependencies-yum.yml
  when: ansible_pkg_mgr == "yum"
