---
- name: Update APT cache
  apt:
    update_cache: yes
  ignore_errors: yes
  become: yes

- name: Check if 'xmlstarlet' is on the PATH
  shell: which xmlstarlet
  register: which_xmlstarlet_cmd
  ignore_errors: yes
  become: yes

- name: Install package 'xmlstarlet'
  apt:
    pkg: xmlstarlet
    state: present
  register: xmlstarlet_install
  when: which_xmlstarlet_cmd.rc != 0
  become: yes
