- name: "Add the -agentpath string to the Glassfish domain.yml at {{ dynatrace_glassfish_agent_glassfish_domain_xml_file }}"
  shell: "xmlstarlet ed -L -s '//java-config' -t elem -n 'jvm-options' -v '{{ dynatrace_glassfish_agent_agentpath_string }}' {{ dynatrace_glassfish_agent_glassfish_domain_xml_file }}"
  when: dynatrace_glassfish_agent_state == "present"
  become: yes

- name: "Remove the -agentpath string from the Glassfish domain.yml at {{ dynatrace_glassfish_agent_glassfish_domain_xml_file }}"
  shell: "xmlstarlet ed -L -d '//java-config/jvm-options[text()={{ dynatrace_glassfish_agent_agentpath_string }}]' {{ dynatrace_glassfish_agent_glassfish_domain_xml_file }}"
  when: dynatrace_glassfish_agent_state == "absent"
  become: yes
